<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\RatingService.Core\RatingService.Core.csproj" />
      <ProjectReference Include="..\RatingService.Infrastructure\RatingService.Infrastructure.csproj" />
      <ProjectReference Include="..\RatingService.Shared\RatingService.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog" Version="4.3.1-dev-02387" />
    </ItemGroup>

</Project>
