syntax = "proto3";

option csharp_namespace = "RatingService.Shared.Protos.GrpcOrderService";
package order;

service OrderService {
  rpc GetAllUserOrders (GetAllUserOrderRequest) returns (GetAllUserOrderResponse);
  rpc GetOrderStatusByProductId (GetOrderStatusByProductIdRequest) returns (GetOrderStatusByProductIdResponse);
}

message GetAllUserOrderRequest {
  string user_id = 1;
}

message OrderProduct {
  string product_id = 2;
}

message GetAllUserOrderResponse {
  repeated OrderProduct items = 1;  
}

message GetOrderStatusByProductIdRequest {
  string product_id = 1;
  string user_id = 2;
}

message GetOrderStatusByProductIdResponse {
  bool exists = 1;
  string status = 2;
}