syntax = "proto3";

option csharp_namespace = "RatingService.Shared.Protos.GrpcProductService";
package product;

service ProductService {
  rpc GetProductsByIds (GetProductsByIdsRequest) returns (GetProductsByIdsResponse);
  rpc UpdateProductStock (UpdateProductStockRequest) returns (UpdateProductStockResponse);
  rpc GetCandidateProductIdsByProdIdsFromReviews(GetCandidateProductIdsByProdIdsFromReviewsRequest) returns (GetCandidateProductIdsByProdIdsFromReviewsResponse);
  rpc GetAllProductsForIndexing (GetAllProductsForIndexingRequest) returns (GetAllProductsForIndexingResponse);
}


message GetProductsByIdsRequest {
  repeated string product_ids = 1;
}

message GetProductsByIdsResponse {
  repeated ProductBrief products = 1;
}

message ProductBrief {
  string id = 1;
  string name = 2;
  int64 price = 3;
  int32 stock_quantity = 4;
  repeated string image_urls = 5;
  string shop_id = 6;
}

message UpdateProductStockRequest {
  repeated StockUpdate updates = 1;
}

message StockUpdate {
  string product_id = 1;
  int32 quantity = 2;
}

message UpdateProductStockResponse {
  bool success = 1;
}

message GetCandidateProductIdsByProdIdsFromReviewsRequest {
  repeated string product_ids_from_reviews = 1;
  string user_id = 2;
}


message GetCandidateProductIdsByProdIdsFromReviewsResponse {
  repeated string product_ids_candidate = 1;
}


message GetAllProductsForIndexingRequest {
  int32 page = 1;
  int32 page_size = 2;
}

message GetAllProductsForIndexingResponse {
  repeated ProductForIndexing products = 1;
  int32 total_count = 2;
}

message ProductForIndexing {
  string id = 1;
  string name = 2;
  repeated string image_urls = 3;
  repeated string category_ids = 4;   
}